#pragma once

namespace Engine
{
	const wstring		g_strTransformTag = TEXT("Com_Transform");

	enum LAYER_ID {
		LAYER_PLAYER, LAYER_MONSTER, LAYER_WEAPON, LAYER_PROJECTILE, LAYER_PLAYER_ATTACK, LAYER_MONSTER_ATTACK, LAYER_VEHICLE,
		LAYER_BACKGROUND, LAYER_CAMERA, LAYER_MAP, LAYER_TELEPORT, LAYER_ENVIRONMENT, LAYER_COIN, LAYER_UI, LAYER_EFFECT, LAYER_END
	};

	enum MOUSEKEYSTATE { DIM_LB, DIM_RB, DIM_MB, DIM_END };
	enum MOUSEMOVESTATE { DIMS_X, DIMS_Y, DIMS_Z, DIMS_END };

	enum DIRECTION
	{
		DIR_B, DIR_F, DIR_L, DIR_R,
		DIR_BL, DIR_BR, DIR_FL, DIR_FR,
		DIR_U, DIR_D, DIR_END
	};

	enum STATE
	{
		// Player

		// ATK
		STATE_ATTACK, STATE_ATTACK2, STATE_ATTACK3, STATE_ATTACK4, STATE_ATTACK5,
		STATE_DASHATTACK, STATE_EAT, STATE_HEAVYATTACK, STATE_HEAVYATTACK2, STATE_HEAVYATTACK3,
		STATE_KILLERSLASH, STATE_KILLERSLASH_L,

		// DEF
		STATE_GUARD_BREAK, STATE_GUARD_HIT, STATE_GUARD_HIT2, STATE_GUARD, STATE_GUARD_LOOP, STATE_GUARD_OUT,

		// DMG
		STATE_BLOWNOFF_IN, STATE_BLOWNOFF_LANDING, STATE_BLOWNOFF_LOOP,
		STATE_DOWN_B_LOOP, STATE_DOWN_B_OUT, STATE_DOWN_F_LOOP, STATE_DOWN_F_OUT, STATE_FORCE,
		STATE_FALLDOWN_HEAVY, STATE_FALLDOWN_LIGHT,
		STATE_HEAVY_HIT, STATE_HEAVY_HIT_F, STATE_HEAVY_HIT_L, STATE_HEAVY_HIT_R,
		STATE_LAUNCHED_B, STATE_LAUNCHED_LOOP, STATE_LAUNCHED_OUT,
		STATE_HIT, STATE_HIT_F, STATE_HIT_L, STATE_HIT_R, STATE_LIGHT_HIT, STATE_LIGHT_HIT_L, STATE_LIGHT_HIT_R,
		STATE_SKILLLOCK, STATE_STRUCKDOWN, STATE_STRUCKDOWN_F,
		STATE_VEHICLE_FALL, STATE_DEATH,

		// EVE
		STATE_FUFORM, STATE_INHALE, STATE_ITEMGET, STATE_RISING, STATE_RISINGUP, STATE_PICKTRASH, STATE_SCORPION,

		// IDL
		STATE_APPEAR_IN, STATE_APPEAR_LOOP, STATE_APPEAR_OUT,
		STATE_TOCOMBAT, STATE_TOIDLE, STATE_IDLE, STATE_TRANSFORM,
		STATE_VEHICLE_IDLE, STATE_VEHICLE_IN_L, STATE_VEHICLE_OUT_L, STATE_VEHICLE_IN_R, STATE_VEHICLE_OUT_R, STATE_VEHICLE_CALL,

		// MOV
		STATE_DODGE, STATE_PERFECTDODGE, STATE_PERFECTDODGE_LOOP, STATE_PERFECTDODGE_OUT, STATE_GRABWEAPON, STATE_SHAKEWEAPON,
		STATE_GUARDWALK, STATE_GUARDWALK_BL, STATE_GUARDWALK_BR, STATE_GUARDWALK_F, STATE_GUARDWALK_FL, STATE_GUARDWALK_FR,
		STATE_GUARDWALK_L, STATE_GUARDWALK_OUT, STATE_GUARDWALK_R,
		STATE_JUMP, STATE_JUMP_LANDING, STATE_JUMP_LANDING_RUN, STATE_JUMP_LANDING_WALK, STATE_JUMP_LOOP,
		STATE_STEPDOWN, STATE_STEPUP, STATE_RUN,
		STATE_VEHICLE_BACK_L, STATE_VEHICLE_BACK_R, STATE_VEHICLE_FAST, STATE_VEHICLE_RUN, STATE_VEHICLE_RUN_START, STATE_VEHICLE_RUN_STOP,
		STATE_WALK, STATE_DEATHKICK, STATE_DEATHKICK_OUT, 
		
		// THROW
		STATE_THROW_LEOPARDON, STATE_THROW_TRIPLEPUT,
		
		// PLAYER END
		STATE_PLAYER_END,

		// ARMOR

		// ATK
		STATE_ARMOR_MISSILE_IN, STATE_ARMOR_MISSILE_LOOP, STATE_ARMOR_MISSILE_OUT,

		// EVE
		STATE_ARMOR_SAPCEJUMP, STATE_ARMOR_TOSTG,

		// IDL
		STATE_ARMOR_IDLE, STATE_ARMOR_TRANSFORM,

		STATE_ARMOR_END,

		// Monster

		// Monster_TriplePut
		// ATK
		STATE_TRIPLEPUT_INVISIBLE, STATE_TRIPLEPUT_INVISIBLE_LOOP, STATE_TRIPLEPUT_INVISIBLE_OUT,
		STATE_TRIPLEPUT_RUSH, STATE_TRIPLEPUT_RUSH_LOOP, STATE_TRIPLEPUT_RUSH_OUT,
		STATE_TRIPLEPUT_SPIN,

		// DMG
		STATE_TRIPLEPUT_DOWN_B, STATE_TRIPLEPUT_DOWN_B_OUT, STATE_TRIPLEPUT_DOWN_F, STATE_TRIPLEPUT_DOWN_F_OUT,
		STATE_TRIPLEPUT_HIT_HEAVY, STATE_TRIPLEPUT_HIT_HEAVY_F, STATE_TRIPLEPUT_HIT_HEAVY_L, STATE_TRIPLEPUT_HIT_HEAVY_R,
		STATE_TRIPLEPUT_HIT, STATE_TRIPLEPUT_HIT_F, STATE_TRIPLEPUT_HIT_L, STATE_TRIPLEPUT_HIT_R,
		STATE_TRIPLEPUT_HIT_LIGHT, STATE_TRIPLEPUT_HIT_LIGHT_L, STATE_TRIPLEPUT_HIT_LIGHT_R,
		STATE_TRIPLEPUT_STUN, STATE_TRIPLEPUT_STUN_OUT, STATE_TRIPLEPUT_THROW,

		// DTH
		STATE_TRIPLEPUT_DOWN_DEATH, STATE_TRIPLEPUT_DOWN_DEATH_F, STATE_TRIPLEPUT_THROW_DEATH,
		STATE_TRIPLEPUT_STAND_DEATH, STATE_TRIPLEPUT_STAND_DEATH_2,

		// IDL
		STATE_TRIPLEPUT_IDLE,

		// MOV
		STATE_TRIPLEPUT_AVOID, STATE_TRIPLEPUT_WALK, STATE_TRIPLEPUT_WALK_F, STATE_TRIPLEPUT_WALK_L, STATE_TRIPLEPUT_WALK_R, STATE_TRIPLEPUT_WALK_STAY,

		STATE_TRIPLEPUT_END,

		// Monster_Leopardon
		// ATK
		STATE_LEOPARDON_OCCURRENCE, STATE_LEOPARDON_WARP, STATE_LEOPARDON_WARP_OUT,
		STATE_LEOPARDON_LASERBEAM, STATE_LEOPARDON_LASERBEAM_LOOP, STATE_LEOPARDON_LASERBEAM_OUT,
		STATE_LEOPARDON_BEAMSWORD, STATE_LEOPARDON_SPREADRING, STATE_LEOPARDON_SQUAREWALL,

		// DMG
		STATE_LEOPARDON_DOWN_B, STATE_LEOPARDON_DOWN_B_OUT, STATE_LEOPARDON_DOWN_F, STATE_LEOPARDON_DOWN_F_OUT,
		STATE_LEOPARDON_HIT_HEAVY, STATE_LEOPARDON_HIT_HEAVY_F, STATE_LEOPARDON_HIT_HEAVY_L, STATE_LEOPARDON_HIT_HEAVY_R,
		STATE_LEOPARDON_HIT, STATE_LEOPARDON_HIT_F, STATE_LEOPARDON_HIT_L, STATE_LEOPARDON_HIT_R,
		STATE_LEOPARDON_STUN, STATE_LEOPARDON_STUN_OUT, STATE_LEOPARDON_THROW,

		// DTH
		STATE_LEOPARDON_DOWN_DEATH, STATE_LEOPARDON_DOWN_DEATH_F, STATE_LEOPARDON_THROW_DEATH, STATE_LEOPARDON_STAND_DEATH,

		// IDLE
		STATE_LEOPARDON_IDLE,

		// CUBE
		STATE_LEOPARDON_CUBE_IDLE,
		STATE_LEOPARDON_CUBE_RUN,

		STATE_LEOPARDON_END,

		// Monster_Bone
		// ATK : 2
		STATE_BONE_ATTACK, STATE_BONE_ATTACK2,
		
		// DMG : 14
		STATE_BONE_DOWN_B, STATE_BONE_DOWN_OUT_B, STATE_BONE_DOWN, STATE_BONE_DOWN_OUT,
		STATE_BONE_HIT_HEAVY_B, STATE_BONE_HIT_HEAVY, STATE_BONE_HIT_HEAVY_L, STATE_BONE_HIT_HEAVY_R,
		STATE_BONE_HIT_LIGHT, STATE_BONE_HIT_LIGHT_L, STATE_BONE_HIT_LIGHT_R,
		STATE_BONE_HIT_DEFAULT_B, STATE_BONE_HIT_DEFAULT, STATE_BONE_HIT_DEFAULT_L, STATE_BONE_HIT_DEFAULT_R,
		STATE_BONE_HIT_STRUCKDOWN_B, STATE_BONE_HIT_STRUCKDOWN,
		STATE_BONE_THROW,
		
		// DTH : 5
		STATE_BONE_DOWN_DEATH_B, STATE_BONE_DOWN_DEATH,
		STATE_BONE_DOWN_FREEZE_B, STATE_BONE_DOWN_FREEZE, STATE_BONE_THROW_DEATH,
		
		// IDL : 5
		STATE_BONE_IDLE_APPEAR, STATE_BONE_IDLE_APPEAR2, STATE_BONE_IDLE,
		STATE_BONE_IDLE_FIND, STATE_BONE_IDLE_FIND2,
		
		// MOV : 5
		STATE_BONE_RUN, STATE_BONE_WALK_B, STATE_BONE_WALK, STATE_BONE_WALK_L, STATE_BONE_WALK_R,

		STATE_BONE_END,

		// Bike
		/*
		// IDL
		STATE_BIKE_IDLE, STATE_BIKE_IDLE_VICTORY,

		// MOV
		STATE_BIKE_FASTTRAVLE, STATE_BIKE_NITRO, STATE_BIKE_NITRO_OUT, STATE_BIKE_NITRO_IN,
		STATE_BIKE_RUN, STATE_BIKE_RUN_BANK_L, STATE_BIKE_RUN_BANK_R, STATE_BIKE_RUN_START, STATE_BIKE_RUN_STOP,
		STATE_BIKE_TURN_L, STATE_BIKE_TURN_R,

		STATE_BIKE_END,
		*/

		// Bike_Cat
		STATE_BIKE_ATTACK_IN, STATE_BIKE_ATTACK, STATE_BIKE_ATTACK_OUT,
		STATE_BIKE_IDLE, STATE_BIKE_IDLE_FACEWASH, STATE_BIKE_IDLE_SIT_IN, STATE_BIKE_IDLE_SIT_LOOK_AROUND, STATE_BIKE_IDLE_SIT, STATE_BIKE_IDLE_SIT_OUT, STATE_BIKE_IDLE_YAWN,
		STATE_BIKE_LIE1, STATE_BIKE_LIE2, STATE_BIKE_LIE3, STATE_BIKE_LIE4, STATE_BIKE_LIE5, STATE_BIKE_LIE6,
		STATE_BIKE_LIE7, STATE_BIKE_LIE8, STATE_BIKE_LIE9, STATE_BIKE_LIE10, STATE_BIKE_LIE11, STATE_BIKE_LIE12, 
		STATE_BIKE_IDLE1, STATE_BIKE_IDLE2, STATE_BIKE_IDLE3, STATE_BIKE_IDLE4, STATE_BIKE_IDLE5, STATE_BIKE_IDLE6, STATE_BIKE_IDLE7, STATE_BIKE_IDLE8,
		STATE_BIKE_IDLE_STRETCHING,
		STATE_BIKE_AVOID, STATE_BIKE_AVOID_L, STATE_BIKE_AVOID_R,
		STATE_BIKE_NITRO, STATE_BIKE_NITRO_IN, STATE_BIKE_NITRO_OUT, STATE_BIKE_RUN1, STATE_BIKE_RUN2, STATE_BIKE_RUN3, STATE_BIKE_JUMP, STATE_BIKE_STEP_2D, STATE_BIKE_STEP_2U, STATE_BIKE_STEP_D, STATE_BIKE_STEP_U,
		STATE_BIKE_RUN, STATE_BIKE_RUN_IN, STATE_BIKE_RUN_OUT, STATE_BIKE_RUN_SPACE,
		STATE_BIKE_MINIGAME_IDLE, STATE_BIKE_MINIGAME_RUN,

		STATE_BIKE_END,

		STATE_END
	};
}